language: nodejs
node_js:
- '0.11'
- '0.10'
install:
- npm install
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- gulp build
deploy:
  provider: npm
  email: hire@roblayton.com
  api:
    key:
      secure: TSZAqSi8p85SMuvts4t6iE1hcSv98x6nvvkD83bA5n00qjQ+BG50XMHUOS7M7tC8CBIKxbtanrjiO3F8iO2SsxR9x2L+3ogcKWe66vJ7RE8CoMqvGdlOZYrqTUe0HwoE6pRN36WIj01MvbgT85qf4yJYw1gs8GRm3FCIpfzPdE4=
  on:
    tags: true
    branch: master
    all_branches: true
