language: nodejs
node_js:
- '0.11'
- '0.10'
install:
- npm install
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- gulp build
deploy:
  provider: npm
  email: hire@roblayton.com
  api_key: HT04VHcdgdtG3zUfVBYa4PGypIUxxUwqvq4S3EPE9+kF+VqJnVqqptrRq4RT7yb/Z2zVYwsHdbo5SpQEXTfzJSkyAf2lK/Nr1GcARh9VVmQ+h3MnW7r35PjXgHQ5QEL5rk1M4pzNvvYmQqNV9SCDjq2iI6aqLeJAFJ13YRmExuY=
  on:
    tags: true
    branch: master
    all_branches: true
