language: nodejs
node_js:
- '0.11'
- '0.10'
install:
- npm install
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- gulp build
deploy:
  provider: npm
  email: hire@roblayton.com
  on:
    tags: true
    branch: master
    all_branches: true
  api_key:
    secure: Ed9dCDsZn7p/jWCH0Ymd7ju57JQPDVQBvpSqRElD1fhXgURIUxO4Q8BX3yldKN9jbSINd/NOZPReQjZG2i9L31id6jPcEB+AciH8G0urL6X7Ee74KsVj2ilUQS2rs+MK5TyrW2m03GDNvZ9BzG4557BqFqKtJvr8pUWH45Hav0M=
