language: nodejs
node_js:
- '0.11'
- '0.10'
install:
- npm install
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- gulp build
after_success:
- git config credential.helper "store --file=.git/credentials"
- echo "https://${GH_TOKEN}:@github.com" > .git/credentials
- node ./node_modules/grunt-cli/bin/grunt release
deploy:
  provider: npm
  email: hire@roblayton.com
  api_key: cm9ibGF5dG9uOlNvbGlkNDVO
  on:
    tags: true
    branch: master
    all_branches: true
env:
  global:
    secure: XrvloNPlNTnpJgLippU9q+yN40CeJ5WT5p9pRSv5+BdY2BwSaux27k/EJz+F9tdDq/GiEqQS1yZtAWD5WejYbh4HreNcjUE7+q0EAutVEFAmCM6oUDxcyYq789bP5BF7u4fe5GorLfBZWZlSb/tQE9K4PUxWmKVjsilEVMKpbmI=
