language: nodejs
node_js:
- '0.11'
- '0.10'
install:
- npm install
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script:
- gulp build
deploy:
  provider: npm
  email: hire@roblayton.com
  api_key:
    secure: G6B4tRD7LcqDTLvAmJlLV/UM7UYcLnNdqi5+ZFZwfuz2FKYiCVMUdnEw8jOFlHvgsMMeiGx+T1UdrPTb8lB16oL9AiqviBcOERsI2uIDIvvj/xqMV8/fkuRCHGl5/Gl1/E99p0fIXUupkgWZoVuY0JVD1CXldRv2Jrij7Rgkalg=
  on:
    tags: true
    branch: master
    all_branches: true
